# Generated by Django 5.2.1 on 2025-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
