# Generated by Django 5.2.1 on 2026-05-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='not provided', max_length=50),
            preserve_default=False,
        ),
    ]
